<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TitanSystems.CodeEditor.UI.WinForms</RootNamespace>
    <AssemblyName>TitanSystems.CodeEditor.UI.WinForms</AssemblyName>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>TitanSystems Monaco Wrapper WPF</Title>
    <Company>TitanSystems</Company>
    <PackageId>TitanSystems.Monaco.Wrapper.WinForms</PackageId>
    <Authors>Thomas Hisgen;TitanSystems</Authors>
    <Product>TitanSystems.Monaco.Wrapper.WinForms</Product>
    <Copyright>TitanSystems</Copyright>
    <Description>A wrapper ui-control for implementing Monaco Editor in WinForms-applicaions.</Description>
    <FileVersion>1.0.1.0</FileVersion>
    <Version>1.0.1</Version>
    <PackageIcon>ttn_monacoeditor.png</PackageIcon>
    <RepositoryUrl>https://github.com/DarkenCreature/TitanSystems.CodeEditor.Wrapper</RepositoryUrl>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2739.15" />
    <PackageReference Include="Nancy" Version="2.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BasicModels\BasicModels.csproj" />
    <ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="license.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="ttn_monacoeditor.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
